### ISSUE TITLE
 Will you implement the Seq2Seq model with added memory module？

### ISSUE THREAD

**Issue by chongyangtao** [mveres01/Theano-LtRRE#1]
Hi, I am trying to implement the Seq2Seq model with added memory module for paper LEARNING TO REMEMBER RARE EVENTS, but I may not understand the GNMT model with added memory module clearly.  Can you supplement the code for this model?  

Thanks!

**Comment by mveres01** [comment]
Hi chongyangtao,

Right now I do not have any plans for adding the seq2seq part of it. But pull requests are welcome if anyone feels like writing that up!
